stages:
  - backend-build
  - backend-test
  - frontned-build
  - frontend-test

backend_build:
  stage: backend-build
  image: gradle:8.3
  tags: [docker]
  rules:
    - changes:
        - backend/**/* 
  script: cd backend && gradle --build-cache clean build bootJar

backend_test:
  stage: backend-test
  image: gradle:8.3
  tags: [docker]
  rules:
    - changes:
        - backend/**/* 
  script: cd backend && gradle clean check

frontend_build:
  stage: frontend-build
  image: node:22
  tags: [docker]
  rules:
    - changes:
        - frontend/**/* 
  script: cd frontend && npm install && npm run build

frontend_test:
  stage: frontend-test
  image: node:22
  tags: [docker]
  rules:
    - changes:
        - frontend/**/* 
  script: cd frontend && npm install && npm run test
