# create a pipeline only for dev and main branches
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - deploy-staging

deploy_staging:
  stage: deploy-staging
  tags: [shell]
  script:
    - mkdir -p /srv/app/staging
    - cd /srv/app/staging
    - rm -rf see
    - git clone http://192.168.56.9/student/see.git
    - ls -l
