# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Shared base box
  config.vm.box = "bento/ubuntu-24.04"

  # Shared provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

  ## ===============================
  ## Integration VM
  ## ===============================
  config.vm.define "integration-server" do |integration|
    integration.vm.hostname = "integration-server"

    integration.vm.network "forwarded_port", guest: 80, host: 8080
    integration.vm.network "private_network", ip: "192.168.56.9"

    integration.vm.synced_folder "./data-integration", "/vagrant_data"

    integration.vm.provider "virtualbox" do |vb|
      vb.memory = 3 * 1024
      vb.cpus = 3
    end

    integration.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~vagrant/.ssh
      cp /vagrant_data/keys/key ~vagrant/.ssh/id_ed25519
      cp /vagrant_data/keys/key.pub ~vagrant/.ssh/id_ed25519.pub
      chown -R vagrant:vagrant ~vagrant/.ssh
      chmod 700 ~vagrant/.ssh
      chmod 600 ~vagrant/.ssh/id_ed25519
      chmod 644 ~vagrant/.ssh/id_ed25519.pub
    SHELL

    integration.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/integration.yml"
    end
  end

  ## ===============================
  ## Deployment VM
  ## ===============================
  config.vm.define "deployment-server" do |deployment|
    deployment.vm.hostname = "deployment-server"

    deployment.vm.network "forwarded_port", guest: 80, host: 8081
    deployment.vm.network "private_network", ip: "192.168.56.10"

    deployment.vm.synced_folder "./data-deployment", "/vagrant_data"

    deployment.vm.provider "virtualbox" do |vb|
      vb.memory = 3 * 1024
      vb.cpus = 3
    end

    deployment.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~vagrant/.ssh
      touch ~vagrant/.ssh/authorized_keys
      cat /vagrant_data/keys/key.pub >> ~vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant ~vagrant/.ssh
      chmod 700 ~vagrant/.ssh
      chmod 600 ~vagrant/.ssh/authorized_keys
    SHELL

    deployment.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/deployment.yml"
    end
  end
end
