# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Shared base box
  config.vm.box = "bento/ubuntu-24.04"

  # Shared provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

  ## ===============================
  ## VM
  ## ===============================
  config.vm.define "integration-server" do |integration|
    integration.vm.hostname = "integration-server"

    integration.vm.network "forwarded_port", guest: 80, host: 8080
    integration.vm.network "forwarded_port", guest: 3001, host: 3001
    integration.vm.network "private_network", ip: "192.168.56.9"

    integration.vm.synced_folder "./data", "/vagrant_data"

    integration.vm.provider "virtualbox" do |vb|
      vb.memory = 5 * 1024
      vb.cpus = 5
    end

    integration.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~vagrant/.ssh
      cp /vagrant_data/keys/key ~vagrant/.ssh/id_ed25519
      cp /vagrant_data/keys/key.pub ~vagrant/.ssh/id_ed25519.pub
      chown -R vagrant:vagrant ~vagrant/.ssh
      chmod 700 ~vagrant/.ssh
      chmod 600 ~vagrant/.ssh/id_ed25519
      chmod 644 ~vagrant/.ssh/id_ed25519.pub
    SHELL

    integration.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/integration.yml"
    end
  end
end
