# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Shared base box
  config.vm.box = "bento/ubuntu-24.04"

  # Shared provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

  ## ===============================
  ## DEV VM
  ## ===============================
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "see-ubuntu"

    dev.vm.network "forwarded_port", guest: 80, host: 8080
    dev.vm.network "private_network", ip: "192.168.56.9"

    dev.vm.synced_folder "./data", "/vagrant_data"

    dev.vm.provider "virtualbox" do |vb|
      vb.memory = 3 * 1024
      vb.cpus = 2
    end

    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/playbook.yml"
    end
  end

  ## ===============================
  ## PROD VM
  ## ===============================
  config.vm.define "prod" do |prod|
    prod.vm.hostname = "see-prod-ubuntu"

    prod.vm.network "forwarded_port", guest: 80, host: 8082
    prod.vm.network "private_network", ip: "192.168.56.11"

    prod.vm.synced_folder "./data-prod", "/vagrant_data"

    prod.vm.provider "virtualbox" do |vb|
      vb.memory = 2 * 1024
      vb.cpus = 2
    end

    prod.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/prod.yml"
    end
  end

  ## ===============================
  ## STAGING VM
  ## ===============================
  config.vm.define "staging" do |staging|
    staging.vm.hostname = "see-staging-ubuntu"

    staging.vm.network "forwarded_port", guest: 80, host: 8081
    staging.vm.network "private_network", ip: "192.168.56.10"

    staging.vm.synced_folder "./data-staging", "/vagrant_data"

    staging.vm.provider "virtualbox" do |vb|
      vb.memory = 2 * 1024
      vb.cpus = 2
    end

    staging.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/staging.yml"
    end
  end
end
